name: Build for all platforms with SCons

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  web-build:
    name: Build for Web (Emscripten)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Emscripten SDK
        uses: rroemhild/setup-emsdk@v1
        with:
          emsdk-version: latest

      - name: Build with SCons for Web
        run: |
          source ./emsdk/emsdk_env.sh
          scons platform=web

  linux-build:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip scons g++

      - name: Build with SCons for Linux
        run: scons platform=linux

  windows-build:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install python --pre -y
          choco install scons -y

      - name: Build with SCons for Windows
        run: scons platform=windows

  macos-build:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install scons

      - name: Build with SCons for macOS
        run: scons platform=macos

  ios-build:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install scons

      - name: Build with SCons for iOS
        run: scons platform=ios ios_simulator=false
