name: Build QuarkPhysics Extension

on:
  workflow_call:
  push:
  pull_request:
  merge_group:

env:
  LIBNAME: example

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Debug templates
          - platform: linux
            float-precision: single
            arch: x86_64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: windows
            float-precision: single
            arch: x86_32
            target-type: template_debug
            os: windows-latest

          - platform: windows
            float-precision: single
            arch: x86_64
            target-type: template_debug
            os: windows-latest

          - platform: macos
            float-precision: single
            arch: universal
            target-type: template_debug
            os: macos-latest

          - platform: android
            float-precision: single
            arch: arm64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: ios
            float-precision: single
            arch: arm64
            target-type: template_debug
            os: macos-latest

          - platform: web
            float-precision: single
            arch: wasm32
            target-type: template_debug
            os: ubuntu-20.04

          # Release templates
          - platform: linux
            float-precision: single
            arch: x86_64
            target-type: template_release
            os: ubuntu-20.04

          # Double precision templates (Debug)
          - platform: linux
            float-precision: double
            arch: x86_64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: windows
            float-precision: double
            arch: x86_32
            target-type: template_debug
            os: windows-latest

          - platform: macos
            float-precision: double
            arch: universal
            target-type: template_debug
            os: macos-latest

          - platform: android
            float-precision: double
            arch: arm64
            target-type: template_debug
            os: ubuntu-20.04

          - platform: ios
            float-precision: double
            arch: arm64
            target-type: template_debug
            os: macos-latest

          - platform: web
            float-precision: double
            arch: wasm32
            target-type: template_debug
            os: ubuntu-20.04

          # Double precision templates (Release)
          - platform: linux
            float-precision: double
            arch: x86_64
            target-type: template_release
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 🔗 GDExtension Build
        uses: ./.github/actions/build
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.float-precision }}
          build-target-type: ${{ matrix.target-type }}

      - name: Windows - Cleanup
        if: ${{ matrix.platform == 'windows' }}
        shell: pwsh
        run: |
          Remove-Item project/addons/quarkphysics/bin/* -Include *.exp,*.lib,*.pdb -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: quarkphysics-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.float-precision }}-${{ matrix.target-type }}
          path: project/addons/quarkphysics/bin/**

  merge:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: quarkphysics-combined
          pattern: quarkphysics-*
          delete-merged: true
